// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Line2u.DTO
{
    public partial class CartDto
    {
        public decimal Id { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public int? Quantity { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public decimal? Status { get; set; }
        public string ProductPrice { get; set; }
        public decimal? ProductId { get; set; }
        public string Guid { get; set; }
        public string AccountUid { get; set; }
        public string ProductGuid { get; set; }
        public string StoreGuid { get; set; }
        public decimal? IsCheckout { get; set; }
    }
}