// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Line2u.DTO
{
    public partial class ChatDto
    {
        public decimal Id { get; set; }
        public string OfficialId { get; set; }
        public string OfficialName { get; set; }
        public string UserName_Receive { get; set; }
        public string UserName_Sender { get; set; }
        public string Sender { get; set; }
        public string Receive { get; set; }
        public string Message { get; set; }
        public string CancelFlag { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public decimal? Status { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Guid { get; set; }
        public string url { get; set; }
        public string AccountUid { get; set; }
    }
}