// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;

namespace Line2u.DTO
{
    public partial class ProductsTrackingDto
    {
        public string ProductName { get; set; }
        public string PhotoPath { get; set; }
        public decimal? Price { get; set; }
       
    }
}