// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Line2u.DTO
{
    public partial class SignarlLoadUseDto
    {
        public string loadUserFrom { get; set; }
        public string loadUserTo { get; set; }
    }
}