// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Line2u.Models
{
    public partial class OrderDetailHistory
    {
        public int PendingQty { get; set; }
        public int ByingQty { get; set; }
        public int CompleteQty { get; set; }
        public bool CancelStatus { get; set; }
        public decimal Id { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public int? Quantity { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
        public string AccountId { get; set; }
        public string OrderDetailGuid { get; set; }
        public string ProductGuid { get; set; }
        public string StoreGuid { get; set; }
    }
}