// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Line2u.Models
{
    public partial class ProductOption
    {
        public decimal Id { get; set; }
        public decimal? ProductId { get; set; }
        public string Topping { get; set; }
        public string Guid { get; set; }
        public string Price { get; set; }
    }
}