// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Line2u.Models
{
    public partial class StoreTable
    {
        public decimal Id { get; set; }
        public decimal? StoreId { get; set; }
        public string TableNumber { get; set; }
        public string Guid { get; set; }
    }
}