// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Line2u.Models
{
    public partial class XAccountPermission
    {
        public decimal Id { get; set; }
        public string UpperGuid { get; set; }
        public string CodeNo { get; set; }
    }
}